//@ sourceMappingURL=bestTick.map
// Generated by CoffeeScript 1.6.1
(function() {

  (typeof exports !== "undefined" && exports !== null ? exports : this).bestTick = (typeof process !== "undefined" && process !== null ? process.nextTick : void 0) || (typeof setImmediate === 'function' && setImmediate) || function(task) {
    return setTimeout(task, 0);
  };

}).call(this);
