// Generated by CoffeeScript 1.6.1
(function() {
  var nextTick, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  nextTick = process.nextTick;

  root.enqueue = (function(queue) {
    var trampoline;
    trampoline = function() {
      var next;
      while (next = queue.shift()) {
        next();
      }
      return queue = void 0;
    };
    return function(f) {
      if (queue != null) {
        return queue.push(f);
      } else {
        queue = [f];
        return nextTick(function() {
          return trampoline();
        });
      }
    };
  })(void 0);

}).call(this);
