//@ sourceMappingURL=index.map
// Generated by CoffeeScript 1.6.1
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Covenant = require('./covenant').Covenant;

  root.Promise = require('./promise').Promise;

}).call(this);
