//@ sourceMappingURL=promise.map
// Generated by CoffeeScript 1.6.1
(function() {
  var Core, Covenant, Promise, root, _ref,
    _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  _ref = typeof window !== "undefined" && window !== null ? window : require('./covenant'), Covenant = _ref.Covenant, Core = _ref.Core;

  Promise = (function(_super) {

    __extends(Promise, _super);

    function Promise(init) {
      var _this = this;
      this._httpResolver = function(res) {
        return Promise.prototype._httpResolver.apply(_this, arguments);
      };
      this._nodeResolver = function(err, value) {
        return Promise.prototype._nodeResolver.apply(_this, arguments);
      };
      this.thenable = function() {
        return Promise.prototype.thenable.apply(_this, arguments);
      };
      this.resolver = function() {
        return Promise.prototype.resolver.apply(_this, arguments);
      };
      Promise.__super__.constructor.call(this, init);
    }

    Promise.pending = function() {
      return new Promise;
    };

    Promise.fulfilled = function(value) {
      return new Promise(function(resolve) {
        return resolve(value);
      });
    };

    Promise.rejected = function(reason) {
      return new Promise(function(__, reject) {
        return reject(reason);
      });
    };

    Promise.fromNode = function(f) {
      return function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return new Promise(function() {
          return f.apply(null, __slice.call(args).concat([this._nodeResolver]));
        });
      };
    };

    Promise.delay = function(ms) {
      return new Promise(function() {
        var _this = this;
        setTimeout((function() {
          return _this.resolve(ms);
        }), ms);
        return this.always(function() {
          return clearTimeout(t);
        });
      });
    };

    Promise.timeout = function(ms, p) {
      return new Promise(function(resolve, reject) {
        var err, t;
        err = new Error("timeout after " + ms + " milliseconds");
        t = setTimeout((function() {
          return reject(err);
        }), ms);
        resolve(p);
        return this.always(function() {
          return clearTimeout(t);
        });
      });
    };

    Promise.when = function() {
      var promises;
      promises = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return new Promise(function(resolve, reject, pAll) {
        var i, p, _i, _len, _results;
        pAll.results = new Array(promises.length);
        pAll.numLeft = promises.length;
        if (promises.length === 0) {
          return resolve([]);
        } else {
          _results = [];
          for (i = _i = 0, _len = promises.length; _i < _len; i = ++_i) {
            p = promises[i];
            _results.push((function(p, i) {
              return Promise._scheduleResolution(pAll, p, i);
            })(p, i));
          }
          return _results;
        }
      });
    };

    Promise.all = Promise.when;

    Promise.prototype.done = function(onFulfill) {
      return this.then(onFulfill);
    };

    Promise.prototype.fail = function(onReject) {
      return this.then(null, onReject);
    };

    Promise.prototype.always = function(callback) {
      return this.then(callback, callback);
    };

    Promise.prototype.resolver = function() {
      return {
        reject: this.reject,
        fulfill: this.fulfill,
        resolve: this.resolve
      };
    };

    Promise.prototype.thenable = function() {
      return {
        then: this.then,
        done: this.done,
        fail: this.fail,
        always: this.always
      };
    };

    Promise._scheduleResolution = function(pAll, valOrPromise, i) {
      if (Promise._isPromise(valOrPromise)) {
        return valOrPromise.then((function(value) {
          return Promise._scheduleResolution(pAll, value, i);
        }), pAll.reject);
      } else {
        pAll.results[i] = valOrPromise;
        if (--pAll.numLeft === 0) {
          return pAll.fulfill(pAll.results);
        }
      }
    };

    Promise._isPromise = function(p) {
      return typeof (p != null ? p.then : void 0) === 'function';
    };

    Promise.prototype._nodeResolver = function(err, value) {
      if (err) {
        return this.reject(err);
      } else {
        return this.fulfill(value);
      }
    };

    Promise.prototype._httpResolver = function(res) {
      if (res.statusCode === 201) {
        return res.pipe(this.stream());
      } else {
        return this.reject(new Error("HTTP status code " + res.statusCode));
      }
    };

    return Promise;

  }).call(this, Core);

  root.Promise = Promise;

}).call(this);
